export const translations = {
    uz: {
        new_project: "Yangi loyihani",
        todo_title: "Vazifalar",
        add_project: "Loyiha qo'shish",
        add_task: "Vazifa qo'shish",
        list_view: "Ro'yxat",
        board_view: "Board",
        search_tasks: "Vazifa qidirish...",
        filter_all: "Barchasi",
        filter_todo: "Bajarilmagan",
        filter_progress: "Jarayonda",
        filter_done: "Bajarilgan",
        no_tasks: "Vazifalar yo'q",
        no_projects: "Loyihalar yo'q. Birinchi loyihani yarating!",
        no_projects_title: "Loyiha yo'q",
        no_projects_desc: "Vazifa qo'shishdan oldin kamida bitta loyiha yarating.",
        status_todo: "Bajarilmagan",
        status_progress: "Jarayonda",
        status_done: "Bajarilgan",
        priority_none: "Prioritet yo'q",
        priority_low: "Past",
        priority_medium: "O'rta",
        priority_high: "Yuqori",
        priority_urgent: "Shoshilinch",
        assignee: "Ijrochi",
        due_date: "Muddat",
        priority: "Prioritet",
        actions: "Amallar",
        task_name_col: "Vazifa nomi",
        edit: "Tahrirlash",
        delete: "O'chirish",
        cancel: "Bekor qilish",
        save: "Saqlash",
        create: "Yaratish",
        modal_create_task: "Yangi vazifa yaratish",
        modal_edit_task: "Vazifani tahrirlash",
        modal_create_project: "Yangi loyiha yaratish",
        task_title_placeholder: "Vazifa nomini kiriting...",
        task_desc_placeholder: "Tavsif (ixtiyoriy)...",
        project_name_placeholder: "Loyiha nomini kiriting...",
        select_assignee: "Ijrochi tanlang",
        select_status: "Status tanlang",
        select_priority: "Prioritet tanlang",
        confirm_delete_task: "Bu vazifani o'chirmoqchimisiz?",
        confirm_delete_project: "Bu loyihani barcha vazifalari bilan o'chirmoqchimisiz?",
        col_todo: "BAJARILMAGAN",
        col_progress: "JARAYONDA",
        col_done: "BAJARILGAN",
        tasks_count: "ta vazifa",
        add_group: "+ Guruh qo'shish",
        empty_column: "Bu yerga vazifalar tashlang",
        project_label: "Loyiha nomi",
        task_label: "Vazifa nomi",
        description_label: "Tavsif",
        status_label: "Status",
        assignee_label: "Ijrochi",
        duedate_label: "Muddat",
        priority_label: "Prioritet",
        overdue: "Muddati o'tgan",
        today: "Bugun",
        no_users_yet: "Foydalanuvchilar yo'q",
        create_time: "Yaratilgan vaqt",
    },
    en: {
        new_project: "New Project",
        todo_title: "Tasks",
        add_project: "Add Project",
        add_task: "Add Task",
        list_view: "List",
        board_view: "Board",
        search_tasks: "Search tasks...",
        filter_all: "All",
        filter_todo: "To Do",
        filter_progress: "In Progress",
        filter_done: "Done",
        no_tasks: "No tasks yet",
        no_projects: "No projects. Create the first one!",
        no_projects_title: "No Project",
        no_projects_desc: "Please create at least one project before adding tasks.",
        status_todo: "To Do",
        status_progress: "In Progress",
        status_done: "Done",
        priority_none: "No priority",
        priority_low: "Low",
        priority_medium: "Medium",
        priority_high: "High",
        priority_urgent: "Urgent",
        assignee: "Assignee",
        due_date: "Due Date",
        priority: "Priority",
        actions: "Actions",
        task_name_col: "Task Name",
        edit: "Edit",
        delete: "Delete",
        cancel: "Cancel",
        save: "Save",
        create: "Create",
        modal_create_task: "Create New Task",
        modal_edit_task: "Edit Task",
        modal_create_project: "Create New Project",
        task_title_placeholder: "Enter task title...",
        task_desc_placeholder: "Description (optional)...",
        project_name_placeholder: "Enter project name...",
        select_assignee: "Select assignee",
        select_status: "Select status",
        select_priority: "Select priority",
        confirm_delete_task: "Delete this task?",
        confirm_delete_project: "Delete this project with all its tasks?",
        col_todo: "TO DO",
        col_progress: "IN PROGRESS",
        col_done: "DONE",
        tasks_count: "tasks",
        add_group: "+ Add Group",
        empty_column: "Drop tasks here",
        project_label: "Project Name",
        task_label: "Task Name",
        description_label: "Description",
        status_label: "Status",
        assignee_label: "Assignee",
        duedate_label: "Due Date",
        priority_label: "Priority",
        overdue: "Overdue",
        today: "Today",
        no_users_yet: "No users yet",
        create_time: "Created at",
    },
    ru: {
        new_project: "Новый проект",
        todo_title: "Задачи",
        add_project: "Добавить проект",
        add_task: "Добавить задачу",
        list_view: "Список",
        board_view: "Доска",
        search_tasks: "Поиск задач...",
        filter_all: "Все",
        filter_todo: "К выполнению",
        filter_progress: "В процессе",
        filter_done: "Выполнено",
        no_tasks: "Задач нет",
        no_projects: "Нет проектов. Создайте первый!",
        no_projects_title: "Нет проекта",
        no_projects_desc: "Создайте хотя бы один проект, прежде чем добавлять задачи.",
        status_todo: "К выполнению",
        status_progress: "В процессе",
        status_done: "Выполнено",
        priority_none: "Без приоритета",
        priority_low: "Низкий",
        priority_medium: "Средний",
        priority_high: "Высокий",
        priority_urgent: "Срочно",
        assignee: "Исполнитель",
        due_date: "Срок",
        priority: "Приоритет",
        actions: "Действия",
        task_name_col: "Название задачи",
        edit: "Редактировать",
        delete: "Удалить",
        cancel: "Отмена",
        save: "Сохранить",
        create: "Создать",
        modal_create_task: "Создать задачу",
        modal_edit_task: "Редактировать задачу",
        modal_create_project: "Создать проект",
        task_title_placeholder: "Введите название задачи...",
        task_desc_placeholder: "Описание (необязательно)...",
        project_name_placeholder: "Введите название проекта...",
        select_assignee: "Выберите исполнителя",
        select_status: "Выберите статус",
        select_priority: "Выберите приоритет",
        confirm_delete_task: "Удалить эту задачу?",
        confirm_delete_project: "Удалить этот проект со всеми задачами?",
        col_todo: "К ВЫПОЛНЕНИЮ",
        col_progress: "В ПРОЦЕССЕ",
        col_done: "ВЫПОЛНЕНО",
        tasks_count: "задач",
        add_group: "+ Добавить группу",
        empty_column: "Перетащите задачи сюда",
        project_label: "Название проекта",
        task_label: "Название задачи",
        description_label: "Описание",
        status_label: "Статус",
        assignee_label: "Исполнитель",
        duedate_label: "Срок",
        priority_label: "Приоритет",
        overdue: "Просрочено",
        today: "Сегодня",
        no_users_yet: "Пользователей нет",
        create_time: "Дата создания",
    },
};

export const TASK_TR = {
    uz: {
        btn: "Tahlil",
        title: "Vazifalar Tahlili",
        sub: "Barcha loyihalar bo'yicha",
        total_tasks: "Jami vazifalar",
        total_done: "Bajarilgan",
        in_progress: "Jarayonda",
        total_projects: "Loyihalar",
        status_dist: "Status taqsimoti",
        priority_dist: "Prioritet taqsimoti",
        top_assignees: "Eng faol ijrochilar",
        projects_prog: "Loyihalar bajarilishi",
        overdue: "Muddati o'tgan",
        done_rate: "Bajarilgan %",
        today_tasks: "Bugungi vazifalar",
        new_this_week: "Yangi (hafta)",
        no_data: "Ma'lumot yo'q",
        todo_lbl: "Bajarilmagan",
        prog_lbl: "Jarayonda",
        done_lbl: "Bajarilgan",
        tasks_lbl: "vazifa",
        footer: "Barcha loyihalar hisobga olindi",
        pri_none: "Prioritet yo'q",
        pri_low: "Past",
        pri_medium: "O'rta",
        pri_high: "Yuqori",
        pri_urgent: "Shoshilinch",
        assignee_tasks: "vazifa",
        overdue_lbl: "Muddati o'tgan",
        project_lbl: "loyiha",
    },
    ru: {
        btn: "Аналитика",
        title: "Аналитика задач",
        sub: "По всем проектам",
        total_tasks: "Всего задач",
        total_done: "Выполнено",
        in_progress: "В процессе",
        total_projects: "Проектов",
        status_dist: "Распределение статусов",
        priority_dist: "По приоритетам",
        top_assignees: "Самые активные",
        projects_prog: "Прогресс проектов",
        overdue: "Просроченные",
        done_rate: "% выполнено",
        today_tasks: "Задачи на сегодня",
        new_this_week: "Новые (неделя)",
        no_data: "Нет данных",
        todo_lbl: "К выполнению",
        prog_lbl: "В процессе",
        done_lbl: "Выполнено",
        tasks_lbl: "задач",
        footer: "Учтены все проекты",
        pri_none: "Без приоритета",
        pri_low: "Низкий",
        pri_medium: "Средний",
        pri_high: "Высокий",
        pri_urgent: "Срочно",
        assignee_tasks: "задач",
        overdue_lbl: "Просрочено",
        project_lbl: "проект",
    },
    en: {
        btn: "Analytics",
        title: "Tasks Analytics",
        sub: "Across all projects",
        total_tasks: "Total Tasks",
        total_done: "Completed",
        in_progress: "In Progress",
        total_projects: "Projects",
        status_dist: "Status Distribution",
        priority_dist: "By Priority",
        top_assignees: "Top Assignees",
        projects_prog: "Project Progress",
        overdue: "Overdue Tasks",
        done_rate: "Completion Rate",
        today_tasks: "Due Today",
        new_this_week: "New (week)",
        no_data: "No data yet",
        todo_lbl: "To Do",
        prog_lbl: "In Progress",
        done_lbl: "Done",
        tasks_lbl: "tasks",
        footer: "All projects are included",
        pri_none: "No priority",
        pri_low: "Low",
        pri_medium: "Medium",
        pri_high: "High",
        pri_urgent: "Urgent",
        assignee_tasks: "tasks",
        overdue_lbl: "Overdue",
        project_lbl: "project",
    },
};
